[package]
name = "resolver-tests"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
cargo = { path = "../.." }
cargo-util = { path = "../cargo-util" }
is-terminal = "0.4.0"
lazy_static = "1.3.0"
proptest = "1.1.0"
varisat = "0.2.1"
