[package]
name = "resolver-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
cargo = { path = "../.." }
cargo-util = { path = "../cargo-util" }
proptest = "0.9.1"
lazy_static = "1.3.0"
varisat = "0.2.1"
atty = "0.2.11"
