[package]
name = "resolver-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
cargo = { path = "../.." }
cargo-util = { path = "../cargo-util" }
is-terminal = "0.4.0"
lazy_static = "1.3.0"
proptest = "0.9.1"
varisat = "0.2.1"
