# Default values: https://probot.github.io/apps/stale/#installation

daysUntilStale: 1160 # ~3 yrs 2 months
daysUntilClose: 30

exemptLabels:
  - C-tracking-issue      # keep tracking issues open
  - C-feature-request     # keep feature requests open (at least for now)
  - "Feature accepted"    # keep accepted features

staleLabel: stale

markComment: >
  As there hasn't been any activity here in a while would someone (the author, a
  team member, or any interested party) be able to summarise the current state,
  perhaps making explicit:
    * Is this still relevant?
    * If so, what is blocking it?
    * Is it known what could be done to help move this forward?

  Thank you!


  (The cargo team is currently evaluating the use of Stale bot, and using #6035
  as the tracking issue to gather feedback.)


  If you're reading this comment from the distant future, fear not if this
  was closed automatically. If you believe it's still an issue please leave a
  comment and a team member can reopen this issue. Opening a new issue is also
  acceptable!

closeComment: >
  As I didn't see any updates in 30 days I'm going to close this.
  Please see the previous comment for more information!

limitPerRun: 1 # 1 per hour, so 24 per day
