language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - ./configure --prefix=$HOME/cargo-install --disable-cross-tests --disable-optimize
  - make
  - make test
  - make distcheck
  - make doc
  - make install
  - make uninstall
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $(uname -s) = Linux ] &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    # apparently we use too much memory and if there's more than one rustc then
    # when compiling Cargo's unit tests some compilers will be randomly kill
    # -9'd
    - CARGOFLAGS=-j1
    - secure: scGpeetUfba5RWyuS4yt10bPoFAI9wpHEReIFqEx7eH5vr2Anajk6+70jW6GdrWVdUvdINiArlQ3An2DeB9vEUWcBjw8WvuPtOH0tDMoSsuVloPlFD8yn1Ac0Bx9getAO5ofxqtoNg+OV4MDVuGabEesqAOWqURNrBC7XK+ntC8=

matrix:
  include:
    - os: osx
      rust: stable
      before_install:
        - export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
        - export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib

branches:
  only:
    - master

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - g++-multilib
      - lib32stdc++6
