language: rust

install:
  - . ./.travis.install.deps.sh

script:
  - ./.travis.check.style.sh
  - make CC="$CC" RUSTC="$RUSTC" -j4
  - make CC="$CC" RUSTC="$RUSTC" test -j4
  - make install DESTDIR=${PWD}/destdir

env:
  - ARCH=i686 CC='cc -m32'
  - ARCH=x86_64 CC=cc

os:
  - linux
  - osx
