language: rust

install:
  - sh ./.travis.install.deps.sh

script:
  - ./configure --local-rust-root=`pwd`/rustc
  - make
  - make test
  - make distcheck

env:
  - BITS=32
  - BITS=64

os:
  - linux
  - osx
