environment:
  CFG_DISABLE_CROSS_TESTS: 1
  matrix:
  - TARGET: i686-pc-windows-msvc
    MSVC: 1
    BITS: 32
    ARCH: x86
  - TARGET: x86_64-pc-windows-msvc
    MSVC: 1
    BITS: 64
    ARCH: amd64
  - TARGET: x86_64-pc-windows-gnu
    ARCH: amd64
    BITS: 64
  - TARGET: i686-pc-windows-gnu
    ARCH: x86
    BITS: 32
    MINGW_URL: https://s3.amazonaws.com/rust-lang-ci
    MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    MINGW_DIR: mingw32

install:
  - IF "%MSVC%"=="" set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - if defined MINGW_URL appveyor DownloadFile %MINGW_URL%/%MINGW_ARCHIVE%
  - if defined MINGW_URL 7z x -y %MINGW_ARCHIVE% > nul
  - if defined MINGW_URL set PATH=%CD%\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%
  - python src/etc/install-deps.py
  - python src/etc/dl-snapshot.py %TARGET%
  - SET PATH=%PATH%;%cd%/rustc/bin
  - SET PATH=%PATH%;%cd%/target/snapshot/bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
