environment:
  CFG_DISABLE_CROSS_TESTS: 1
  matrix:
  - TARGET: i686-pc-windows-msvc
    MSVC: 1
    BITS: 32
    ARCH: x86
  - TARGET: x86_64-pc-windows-msvc
    MSVC: 1
    BITS: 64
    ARCH: amd64
  - TARGET: x86_64-pc-windows-gnu
    ARCH: amd64
    BITS: 32
  - TARGET: i686-pc-windows-gnu
    ARCH: x86
    BITS: 64

install:
  - IF "%MSVC%"=="" set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - python src/etc/install-deps.py
  - python src/etc/dl-snapshot.py %TARGET%
  - SET PATH=%PATH%;%cd%/rustc/bin
  - SET PATH=%PATH%;%cd%/target/snapshot/bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
