[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1.4"
url = "0.2.0"
semver = "0.1.0"
curl = "0.1.0"
tar = "0.1.0"
flate2 = "0.1.0"
git2 = "0.1.0"
glob = "0.1.0"
time = "0.1.0"
log = "0.1.0"

[dependencies.docopt]
git = "https://github.com/alexcrichton/docopt.rs"
branch = "update"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
