[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1.18"
semver = "0.1.16"
curl = "0.2.2"
tar = "0.2.3"
flate2 = "0.2.0"
git2 = "0.2.1"
git2-curl = "0.2.1"
glob = "0.2.2"
time = "0.1.19"
log = "0.3.0"
env_logger = "0.3"
docopt = "0.6.45"
url = "0.2.23"
rustc-serialize = "0.3.1"
term = "0.2"
regex = "0.1.18"
threadpool = "0.1.1"
libc = "0.1.2"
registry = { path = "src/registry" }

[target.i686-pc-windows-gnu]
dependencies = { winapi = "0.1", advapi32-sys = "0.1", kernel32-sys = "0.1" }
[target.x86_64-pc-windows-gnu]
dependencies = { winapi = "0.1", advapi32-sys = "0.1", kernel32-sys = "0.1" }

[dev-dependencies]
tempdir = "0.3"
hamcrest = { git = "https://github.com/carllerche/hamcrest-rust.git" }

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
