[package]
name = "cargo"
version = "0.30.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "https://docs.rs/cargo"
description = """
Cargo, a package manager for Rust.
"""

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
atty = "0.2"
crates-io = { path = "src/crates-io", version = "0.18" }
crossbeam = "0.3"
crypto-hash = "0.3.1"
curl = "0.4.12"
env_logger = "0.5.4"
failure = "0.1.1"
filetime = "0.2"
flate2 = "1.0"
fs2 = "0.4"
git2 = "0.7.2"
git2-curl = "0.8.1"
libgit2-sys = "0.7.5" # required only for minimal-versions. brought in by git2 and git2-curl.
libssh2-sys = "0.2.8" # required only for minimal-versions. brought in by libgit2-sys.
glob = "0.2.11"
hex = "0.3"
home = "0.3"
ignore = "0.4"
lazy_static = "1.0.0"
jobserver = "0.1.11"
lazycell = "1.0"
libc = "0.2"
log = "0.4"
num_cpus = "1.0"
rustfix = "0.4"
same-file = "1"
semver = { version = "0.9.0", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_ignored = "0.0.4"
serde_json = "1.0"
shell-escape = "0.1"
tar = { version = "0.4.15", default-features = false }
tempfile = "3.0"
termcolor = "1.0"
toml = "0.4.2"
url = "1.1"
clap = "2.31.2"
unicode-width = "0.1.5"

# Not actually needed right now but required to make sure that rls/cargo build
# with the same set of features in rust-lang/rust
num-traits = "0.2" # enable the default feature

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { version = "0.6.0", features = ["mac_os_10_7_support"] }

[target.'cfg(windows)'.dependencies]
miow = "0.3.1"

[target.'cfg(windows)'.dev-dependencies]
gcc = "0.3.23" # required only for minimal-versions on windows. brought in by flate2 and others.
cmake = "0.1.24" # required only for minimal-versions on windows. brought in as build-dependencie on libgit2-sys.

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
  "basetsd",
  "handleapi",
  "jobapi",
  "jobapi2",
  "memoryapi",
  "minwindef",
  "ntdef",
  "ntstatus",
  "processenv",
  "processthreadsapi",
  "psapi",
  "synchapi",
  "winerror",
  "winbase",
  "wincon",
  "winnt",
]

[dev-dependencies]
bufstream = "0.1"

[[bin]]
name = "cargo"
test = false
doc = false
