[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[profile.test]
debug = false
[profile.dev]
debug = false

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1.7"
semver = "0.1.6"
curl = "0.1.3"
tar = "0.1.3"
flate2 = "0.1.0"
git2 = "0.1.0"
glob = "0.1.0"
time = "0.1.0"
log = "0.1.0"
docopt = "0.6.19"
url = "0.2.7"
rustc-serialize = "0.1.5"
term = "0.1"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
