[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1.18"
semver = "0.1.16"
curl = "0.2.2"
tar = "0.2.3"
flate2 = "0.2.0"
git2 = "0.2.1"
git2-curl = "0.2.1"
glob = "0.2.2"
time = "0.1.19"
log = "0.2.5"
env_logger = "0.2.2"
docopt = "0.6.45"
url = "0.2.23"
rustc-serialize = "0.3.1"
term = "0.1.13"
regex = "0.1.18"
threadpool = "0.1.1"
libc = "0.1.2"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.1"
advapi32-sys = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.1"
advapi32-sys = "*"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"
[[bench]]
name = "tests"
path = "tests/tests.rs"

[[test]]
name = "resolve"
