[project]
name = "cargo"
version = "0.0.1-pre"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies.docopt]
git = "https://github.com/docopt/docopt.rs"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies.semver]
git = "https://github.com/rust-lang/semver"

[dependencies.curl]
git = "https://github.com/alexcrichton/curl-rust"
branch = "bundle"

[dependencies.tar]
git = "https://github.com/alexcrichton/tar-rs"

[dependencies.flate2]
git = "https://github.com/alexcrichton/flate2-rs"

[dependencies.git2]
git = "https://github.com/alexcrichton/git2-rs"
branch = "no-build-cmd"

[dependencies.glob]
git = "https://github.com/rust-lang/glob"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
