[project]

name = "cargo"
version = "0.0.1-pre"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>"]

[[lib]]

name = "cargo"
path = "src/cargo/lib.rs"

# TODO: remove all these `rev` markers once we have an official lockfile
[dependencies.docopt]
git = "https://github.com/burntsushi/docopt.rs"
rev = "fd2377d"

[dependencies.docopt_macros]
git = "https://github.com/burntsushi/docopt.rs"
rev = "fd2377d"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"
rev = "7e1c1e1"

[dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
rev = "c23b876"

[dependencies.url]
git = "https://github.com/servo/rust-url"
rev = "3d54552"

[dependencies.semver]
git = "https://github.com/rust-lang/semver"
rev = "e17191f"


[[bin]]
name = "cargo"
test = false

[[bin]]
name = "cargo-build"
test = false

[[bin]]
name = "cargo-clean"
test = false

[[bin]]
name = "cargo-git-checkout"
test = false

[[bin]]
name = "cargo-read-manifest"
test = false

[[bin]]
name = "cargo-run"
test = false

[[bin]]
name = "cargo-rustc"
test = false

[[bin]]
name = "cargo-test"
test = false

[[bin]]
name = "cargo-verify-project"
test = false

[[bin]]
name = "cargo-version"
test = false

[[bin]]
name = "cargo-new"
test = false

[[bin]]
name = "cargo-doc"
test = false

[[bin]]
name = "cargo-generate-lockfile"
test = false

[[bin]]
name = "cargo-update"
test = false

[[test]]
name = "tests"
