[project]
name = "cargo"
version = "0.2.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
curl = "0.2"
docopt = "0.6"
env_logger = "0.3"
flate2 = "0.2"
git2 = "0.2"
git2-curl = "0.2"
glob = "0.2"
libc = "0.1"
log = "0.3"
num_cpus = "0.1"
regex = "0.1"
registry = { path = "src/registry" }
rustc-serialize = "0.3"
semver = "0.1"
tar = "0.2"
term = "0.2"
threadpool = "0.1"
time = "0.1"
toml = "0.1"
url = "0.2"

[target.i686-pc-windows-gnu]
dependencies = { winapi = "0.1", advapi32-sys = "0.1", kernel32-sys = "0.1" }
[target.x86_64-pc-windows-gnu]
dependencies = { winapi = "0.1", advapi32-sys = "0.1", kernel32-sys = "0.1" }

[dev-dependencies]
tempdir = "0.3"
hamcrest = { git = "https://github.com/carllerche/hamcrest-rust.git" }

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
