[project]

name = "cargo"
version = "0.0.1-pre"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>"]

[lib]

name = "cargo"
path = "src/cargo/lib.rs"

[dependencies.docopt]
git = "https://github.com/burntsushi/docopt.rs"

[dependencies.docopt_macros]
git = "https://github.com/burntsushi/docopt.rs"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies.semver]
git = "https://github.com/rust-lang/semver"

[dependencies.git2]
git = "https://github.com/alexcrichton/git2-rs"

[[bin]]
name = "cargo"
test = false

[[bin]]
name = "cargo-build"
test = false

[[bin]]
name = "cargo-clean"
test = false

[[bin]]
name = "cargo-git-checkout"
test = false

[[bin]]
name = "cargo-read-manifest"
test = false

[[bin]]
name = "cargo-run"
test = false

[[bin]]
name = "cargo-rustc"
test = false

[[bin]]
name = "cargo-test"
test = false

[[bin]]
name = "cargo-bench"
test = false

[[bin]]
name = "cargo-verify-project"
test = false

[[bin]]
name = "cargo-version"
test = false

[[bin]]
name = "cargo-new"
test = false

[[bin]]
name = "cargo-doc"
test = false

[[bin]]
name = "cargo-generate-lockfile"
test = false

[[bin]]
name = "cargo-update"
test = false

[[test]]
name = "tests"
