[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1.4"
semver = "0.1.0"
curl = "0.1.0"
url = "0.2.7"
tar = "0.1.0"
flate2 = "0.1.0"
git2 = "0.1.0"
glob = "0.1.0"
time = "0.1.0"
log = "0.1.0"
docopt = "0.6.18"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
