[ping.windows]
message = """\
Hey Windows Group! This bug has been identified as a good "Windows candidate".
In case it's useful, here are some [instructions] for tackling these sorts of
bugs. Maybe take a look?
Thanks! <3

[instructions]: https://rustc-dev-guide.rust-lang.org/notification-groups/windows.html
"""
label = "O-windows"

[shortcut]

[autolabel."S-waiting-on-review"]
new_pr = true

[assign]
contributing_url = "https://rust-lang.github.io/cargo/contrib/"

[assign.owners]
"*" = ["@ehuss", "@epage", "@weihanglo"]
