[package]
name = "capture"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Tool for capturing a real-world workspace for benchmarking."

[dependencies]
cargo_metadata.workspace = true
flate2.workspace = true
tar.workspace = true
toml.workspace = true
