[package]
name = "capture"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Tool for capturing a real-world workspace for benchmarking."

[dependencies]
cargo_metadata = "0.14.0"
flate2 = { version = "1.0.3", default-features = false, features = ["zlib"] }
tar = { version = "0.4.35", default-features = false }
toml = "0.5.8"
