[package]
name = "cargo-credential-gnome-secret"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cargo-credential = { path = "../cargo-credential" }

[build-dependencies]
pkg-config = "0.3.19"
