[book]
title = "Cargo Contributor Guide"
authors = ["Eric Huss"]

[output.html]
git-repository-url = "https://github.com/rust-lang/cargo/tree/master/src/doc/contrib/src"

[output.html.redirect]
"/apidoc/cargo/" = "https://doc.rust-lang.org/nightly/nightly-rustc/cargo/"
