[package]
name = "cargo-credential-wincred"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/cargo"
description = "A Cargo credential process that stores tokens with Windows Credential Manager."

[dependencies]
cargo-credential = { version = "0.2.0", path = "../cargo-credential" }
windows-sys = { version = "0.45", features = ["Win32_Foundation", "Win32_Security_Credentials"] }
