[package]
name = "cargo-test-support"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.34"
cargo-test-macro = { path = "../cargo-test-macro" }
cargo-util = { path = "../cargo-util" }
crates-io = { path = "../crates-io" }
filetime = "0.2"
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }
git2 = "0.17.0"
glob = "0.3"
itertools = "0.10.0"
lazy_static = "1.0"
pasetors = { version = "0.6.4", features = ["v3", "paserk", "std", "serde"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0"
snapbox = { version = "0.4.0", features = ["diff", "path"] }
tar = { version = "0.4.38", default-features = false }
termcolor = "1.1.2"
time = { version = "0.3", features = ["parsing", "formatting"]}
toml = "0.7.0"
url = "2.2.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.45.0", features = ["Win32_Storage_FileSystem"] }
