[package]
name = "cargo-test-support"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
cargo = { path = "../.." }
filetime = "0.2"
flate2 = "1.0"
git2 = "0.10"
glob = "0.3"
lazy_static = "1.0"
remove_dir_all = "0.5"
serde_json = "1.0"
tar = "0.4"
url = "2.0"
