[package]
name = "registry"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "registry"
path = "lib.rs"

[dependencies.curl]
git = "https://github.com/carllerche/curl-rust"
