[package]
name = "cargo-credential-macos-keychain"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cargo-credential = { path = "../cargo-credential" }
security-framework = "2.0.0"
